//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int ID { get; set; }
        public int UsersID { get; set; }
        public int TovarID { get; set; }
    
        public virtual users users { get; set; }
        public virtual tovary tovary { get; set; }
    }
}
