//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TovaryCart
    {
        public int TovaryID { get; set; }
        public int CartID { get; set; }
        public int TCID { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual tovary tovary { get; set; }
    }
}
